[book]
authors = ["Shawn Wang"]
language = "en"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/shawn111/dotfiles"
edit-url-template = "https://github.com/shawn111/dotfiles/edit/main/{path}"

[preprocessor.presentation-preprocessor]
