[book]
authors = ["Shawn Wang"]
language = "en"
multilingual = false
src = "."

[output.html]
git-repository-url = "https://github.com/shawn111/dotfiles"
edit-url-template = "https://github.com/shawn111/dotfiles/edit/main/{path}"

[preprocessor.presentation-preprocessor]


[preprocessor.cmdrun]


[preprocessor.autosummary]
# This is so that mdBook doesn't start regenerating
# deleted folders before autosummary can remove them from SUMMARY.md

# If true, files that start with . or _ are ignored.
ignore-hidden = true

[build]
create-missing = false
build-dir = "_book"
